apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f project02_unificado.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-server
  name: nginx-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-server
    spec:
      containers:
      - image: nginx
        name: nginx-server
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-server-claim0
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-server-claim0
        persistentVolumeClaim:
          claimName: nginx-server-claim0
          readOnly: true
status: {}
