version: '3'

services:
  nginx-server:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - reactpj
      - nodepj
  reactpj:
    container_name: reactpj
    restart: always
    build: ./frontend/periodico
    volumes:
      - ./frontend/periodico:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - nodepj
  nodepj:
    container_name: nodepj
    restart: always
    build: ./backend
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - projectdb
  projectdb:
    container_name: projectdb
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jmejiao5
      MONGO_INITDB_ROOT_PASSWORD: fsfRAJ87
      MONGO_INITDB_DATABASE: project01
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro