version: '3'

services:
  node-api:
    container_name: node-api
    restart: always
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
networks:
  default:
    external:
      name: database_topicos
