apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f project02_unificado.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: projectdb
  name: projectdb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: projectdb
status:
  loadBalancer: {}
