apiVersion: v1
kind: PersistentVolume
metadata:
 name: projectdb-vol
 labels:
  type: local
  io.kompose.service: projectdb-claim0
spec:
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: projectdb-vol-claim0
 creationTimestamp: null
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
status: {}
